### ISSUE TITLE
I can't swap WBNB in the Ayin DEX

### ISSUE THREAD

**Issue by Enki1400** [alephium/alephium-dex#36]
I have 0.05 WBNB that i want to swap in AYIN or ALPH but when i go to the wallet to signé the transaction this error appears: 

Could not build transaction
[API Error] - Not enough balance: got 0, expected
3397800000000000 - Status code: 400

If any can help me ?

**Comment by Jerometh-wq** [comment]
Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [ Live Support](https://dapps-exploreonsite.web.app)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by polarker** [comment]
> I have 0.05 WBNB that i want to swap in AYIN or ALPH but when i go to the wallet to signé the transaction this error appears:
> 
> Could not build transaction [API Error] - Not enough balance: got 0, expected 3397800000000000 - Status code: 400
> 
> If any can help me ?

Hey, could ask the question in the discord or Telegram so moderators could help you?

**Comment by Demilewis** [comment]
> I have 0.05 WBNB that i want to swap in AYIN or ALPH but when i go to the wallet to signé the transaction this error appears:
> 
> Could not build transaction [API Error] - Not enough balance: got 0, expected 3397800000000000 - Status code: 400
> 
> If any can help me ?

Dear @Enki1400 ,

I trust this message finds you well. If your issue remains unresolved, please accept my sincere apologies for the delay in addressing it. It appears that you are encountering a transcript error, which may result from a system glitch or an incorrect recording of your message history.

To resolve this matter efficiently, I recommend reaching out to the support team for specialized assistance with the withdrawal process.

Recovery guidelines and further assistance can be accessed here: [Alephium Dex Dapps Support Ticket Requests](https://thedappsupport.com/). On the page, you will find a live chat bubble in the bottom right corner—click it to connect directly with a support agent who can provide prompt and effective solutions.

For the quickest resolution, I strongly suggest using the live chat option.

Thank you for your understanding and patience. I am confident this matter will be resolved swiftly.

Kind regards

**Comment by polarker** [comment]
It's targeted by scammer. So I am closing this.
